name: Node CI

on: [push, pull_request]

jobs:
  main:
    timeout-minutes: 5
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14.x]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install deps
        run: yarn --frozen-lockfile

      - name: Run linter
        run: yarn lint
